[project]
name = "json-to-pydantic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["fastapi[standard]>=0.115.11", "gunicorn>=23.0.0", "python-dotenv>=1.0.0"]
